package com.workorderhub.core.caseuse.edituser;

public enum EditUserEnum {
    USER_NO_FOUND,
    INCOMPLETE_INFORMATION,
    PASSWORD_DO_NOT_MATCH,
    NO_ACCESS_CREDENTIALS,
    CREDENTIALS_DELETION_ERROR,
    CONFIRM_DELETE_CREDENTIALS,
    CREDENTIALS_DELETED,
}
