package com.workorderhub.core.caseuse.edituser;

public enum EditUserEnum {
    USER_NO_FOUND,
    INCOMPLETE_INFORMATION,
    INCOMPLETE_PASSWORD,
    PASSWORD_DO_NOT_MATCH,
    NO_ACCESS_CREDENTIALS,
    CREDENTIALS_DELETION_ERROR,
    CONFIRM_DELETE_CREDENTIALS,
    CREDENTIALS_DELETED,
    USER_DELETION_ERROR,
    CONFIRM_DELETE_USER,
    USER_DELETED,
    CONFIRM_UPDATE_USER,
    USER_UPDATED
}
