package com.workorderhub.core.caseuse.technician;

public enum TechnicianEnum{
    WORK_ORDER_ID_ERROR,
    WORK_ORDER_NOT_FOUND,
    WORK_ORDER_START_SUCCESS,
    WORK_ORDER_START_ERROR,
    REQUEST_CONFIRMATION_START_WORK_ORDER,
    REQUEST_CONFIRMATION_CLOSE_WORK_ORDER,
    REQUEST_CONFIRMATION_DELETE_WORK_ORDER,
    WORK_ORDER_DELETE_SUCCESS,
    WORK_ORDER_DELETE_ERROR,
    WORK_ORDER_CLOSE_SUCCESS,
    WORK_ORDER_CLOSE_ERROR
}
