package com.workorderhub.core.gateway;

import com.workorderhub.core.entity.Category;

import java.util.List;

public interface CategoryGateway {

    /**
     * Retrieves a list of all categories from the database.
     * @return A list of Category objects representing all categories in the database.
     */
    List<Category> getCategoryList();

    /**
     * Retrieves the ID of a category based on its name.
     * @param category The Category object containing the name and description.
     * @return The ID of the category if found, or 0 if the category does not exist in the database.
     */
    int getCategoryId(Category category);

    /**
     * Inserts a new category into the database.
     * @param category The Category object containing the name and description.
     * @return Autogenerated ID of the newly inserted category if the insertion is successful, or 0 if the insertion fails.
     */
    int insertCategory(Category category);

    /**
     * Deletes an existing category from the database.
     * @param category The Category object containing the name and description.
     * @return true if the deletion is successful, or false otherwise.
     */
    boolean deleteCategory(Category category);

    /**
     * Updates an existing category in the database.
     * @param category The Category object containing the name and description.
     * @return true if the update is successful, or false otherwise.
     */
    boolean updateCategory(Category category);
}
