package com.workorderhub.core.gateway;

import com.workorderhub.core.entity.Credentials;

public interface CredentialsGateway {

    /**
     * Gets the credentials ID by the user credentials.
     *
     * @param credentials Credentials provided by the user.
     * @return Credentials ID.
     */
    int getCredentialsId(Credentials credentials);

    /**
     * Gets the user credentials by the ID.
     *
     * @param id Credentials ID.
     * @return User credentials.
     */
    Credentials getCredentialsById(int id);

    /**
     * Inserts new user credentials. The database generates the ID.
     *
     * @param credentials Credentials provided by the user.
     * @return Autogenerated ID of the new credentials.
     */
    int insertCredentials(Credentials credentials);

    /**
     * Deletes the user credentials from the database.
     *
     * @param credentials Credentials provided by the user.
     * @return True if the elimination is successful, false if not.
     */
    boolean deleteCredentials(Credentials credentials);

    /**
     * Updates the user credentials.
     *
     * @param credentials Credentials provided by the user.
     * @return True if the update is successful, false if not.
     */
    boolean updateCredentials(Credentials credentials);
}
