package com.workorderhub.core.gateway;

import com.workorderhub.core.entity.LotoProcedure;

import java.util.List;

public interface LotoProcedureGateway {

    /**
     * Gets the LOTO procedure list.
     * @return List of LOTO procedure objects.
     */
    List<LotoProcedure> getLotoProceduresList();

    /**
     * Inserts a new LOTO procedure.
     * @return Autogenerated LOTO procedure ID.
     */
    int insertProcedure(LotoProcedure lotoProcedure);

    /**
     * Deletes a LOTO procedure.
     * @param documentId LOTO procedure ID to delete.
     * @return True if is successfully deleted, false if not.
     */
    boolean deleteProcedure(int documentId);

    /**
     * Updates a LOTO procedure name.
     * @param documentId LOTO procedure ID to update.
     * @param newName New name to update.
     * @return True if is successfully updated, false if not.
     */
    boolean updateProcedureName(int documentId, String newName);

    /**
     * Updates a LOTO procedure code.
     * @param documentId LOTO procedure ID to update.
     * @param newCode New code to update.
     * @return True if is successfully updated, false if not.
     */
    boolean updateProcedureCode(int documentId, String newCode);

    /**
     * Gets a LOTO procedure by its document ID.
     * @param documentId LOTO procedure ID to retrieve.
     * @return LOTO object if found, null if not found.
     */
    LotoProcedure getLotoProcedureById(int documentId);
}
