package com.workorderhub.core.gateway;

import com.workorderhub.core.entity.LotoProcedure;

import java.util.List;

public interface LotoProcedureGateway {

    /**
     * Gets the LOTO procedure list.
     * @return List of LOTO procedure objects.
     */
    List<LotoProcedure> getWorkProcedures();

    /**
     * Inserts a new LOTO procedure.
     * @return Autogenerated LOTO procedure ID.
     */
    int insertProcedure(LotoProcedure lotoProcedure);

    /**
     * Deletes a LOTO procedure.
     * @param lotoProcedure LOTO procedure to delete.
     * @return True if is successfully deleted, false if not.
     */
    boolean deleteProcedure(LotoProcedure lotoProcedure);

    /**
     * Updates a LOTO procedure.
     * @param lotoProcedure LOTO procedure to delete.
     * @return True if is successfully updated, false if not.
     */
    boolean updateProcedure(LotoProcedure lotoProcedure);
}
