package com.workorderhub.core.gateway;

import com.workorderhub.core.entity.User;
import com.workorderhub.core.entity.UserRoleEnum;

import java.util.List;

public interface UserGateway {
    List<User> getAllUser();
    List<User> getUsersByRole(UserRoleEnum userRole);

    /**
     * Gets the user to edit the user information.
     *
     * @param name  User name
     * @param email Email
     * @return Retrieved user.
     */
    User getUser(String name, String email);

    /**
     * Gets the user by user credentials. It is used to access to the app.
     *
     * @param idCredentials Credentials ID.
     * @return Retrieved user.
     */
    User getUserByCredentials(int idCredentials);

    /**
     * Inserts a new user. The database generates the ID.
     *
     * @param user New user.
     * @return Autogenerated ID of the new user.
     */
    int insertUser(User user);

    /**
     * Remove the user from the database.
     *
     * @param user User to delete.
     * @return True if the elimination is successful, false if not.
     */
    boolean deleteUser(User user);

    /**
     * Updates the user information.
     *
     * @param user User to update.
     * @return True if the update is successful, false if not.
     */
    boolean updateUser(User user);
}
