package com.workorderhub.core.gateway;

import com.workorderhub.core.entity.WorkProcedure;

import java.util.List;

public interface WorkProcedureGateway {

    /**
     * Gets the work procedure list.
     * @return List of work procedure objects.
     */
    List<WorkProcedure> getWorkProcedureList();

    /**
     * Inserts a new work procedure.
     * @return Autogenerated work procedure ID.
     */
    int insertProcedure(WorkProcedure workProcedure);

    /**
     * Deletes a work procedure.
     * @param documentId work procedure ID to delete.
     * @return True if is successfully deleted, false if not.
     */
    boolean deleteProcedure(int documentId);

    /**
     * Updates a work procedure.
     * @param workProcedure work procedure to delete.
     * @return True if is successfully updated, false if not.
     */
    boolean updateProcedure(WorkProcedure workProcedure);
}
