package com.workorderhub.core.gateway;

import com.workorderhub.core.entity.WorkProcedure;

import java.util.List;

public interface WorkProcedureGateway {

    /**
     * Gets the work procedure list.
     * @return List of work procedure objects.
     */
    List<WorkProcedure> getWorkProcedureList();

    /**
     * Inserts a new work procedure.
     * @return Autogenerated work procedure ID.
     */
    int insertProcedure(WorkProcedure workProcedure);

    /**
     * Deletes a work procedure.
     * @param documentId work procedure ID to delete.
     * @return True if is successfully deleted, false if not.
     */
    boolean deleteProcedure(int documentId);

    /**
     * Updates a work procedure name.
     * @param documentId work procedure ID to update.
     * @param newName New name to update.
     * @return True if is successfully updated, false if not.
     */
    boolean updateProcedureName(int documentId, String newName);

    /**
     * Updates a work procedure code.
     * @param documentId work procedure ID to update.
     * @param newCode New code to update.
     * @return True if is successfully updated, false if not.
     */
    boolean updateProcedureCode(int documentId, String newCode);

    /**
     * Gets a work procedure by its ID.
     * @param documentId work procedure ID to retrieve.
     * @return WorkProcedure object if found, null if not found.
     */
    WorkProcedure getWorkProcedureById(int documentId);
}
