package com.workorderhub.core.caseuse.workorder;

public enum WorkOrderEnum {
    NO_PLANT_ELEMENT,
    NO_TECHNICIANS,
    NO_SUPERVISORS,
    WORK_ORDER_DESCRIPTION_ERROR,
    WORK_ORDER_CATEGORY_ERROR,
    WORK_ORDER_HOLDER_ERROR,
    WORK_ORDER_PLANT_ELEMENT_ERROR,
    WORK_ORDER_CREATED,
    WORK_ORDER_CREATION_ERROR,
    WORK_PERMIT_DESCRIPTION_ERROR,
}
