# Main Screen
mainScreen.width = 900.0
mainScreen.height = 600.0

# Manager Main Menu
adminMenu.plantElementWidth = 1000.0
adminMenu.plantElementHeight = 620.0
adminMenu.sparePartsWidth = 1000.0
adminMenu.sparePartsHeight = 786.0
adminMenu.workOrderWidth = 1366.0
adminMenu.workOrderHeight = 768.0

# Work Order Review - Technician
technicianView.workOrderReviewWidth = 1040.0
technicianView.workOrderReviewHeight = 600.0

# Work Order Review - Supervisor
supervisorView.workOrderReviewWidth = 1040.0
supervisorView.workOrderReviewHeight = 600.0