#Data Base Connection
database.URL = jdbc:mysql:// localhost:3306/order_hub
database.username = root
database.password = admin
database.connector = com.mysql.cj.jdbc.Driver


# Login view
login.default = Order Hub
login.userNoFound = New User
login.defaultStyle = -fx-background-color: black; -fx-text-fill: white
login.failStyle = -fx-background-color: red; -fx-text-fill: black
login.managerScreen = Order Hub - Manager
login.supervisorScreen = Order Hub - Supervisor
login.technicianScreen = Order Hub - Technician

# Manager Main view
adminView.loggedUser = User:

adminView.workOrderId = Work Order ID
adminView.startDate = Start Date
adminView.endDate = End Date
adminView.workProcedureCode = Work Procedure Code
adminView.lockOutDeviceId = Lock Device ID
adminView.lotoProcedureCode = LOTO Procedure Code
adminView.holderName = Holder
adminView.plantElement = Plant Element Tag
adminView.status = Status
adminView.workLogId = Work Log ID
adminView.workLogDate = Record Date
adminView.workLogComment = Action
adminView.employeeName = Carried Out By
adminView.workPermit = Work Permit Included

adminView.logDate.noSelectedTitle = Warning
adminView.logDate.noSelectedMessage = Please, select a date.

# Manager Main Menu
adminMenu.newUserTittle = New User
adminMenu.editUserTittle = Edit User
adminMenu.proceduresTittle = Work and LOTO Procedures
adminMenu.plantElementsTittle = Equipment and Instrument elements
adminMenu.sparePartsTittle = Spare Parts Inventory
adminMenu.newWorkOrderTitle = Open Work Order
adminMenu.editWorkOrderTitle = Edit Work Order

adminMenu.noSelectedTitle = Warning
adminMenu.noSelectedMessage = Please, select a work order from the list.


#Add user form
addUserView.default = New User
addUserView.defaultStyle = -fx-background-color: black; -fx-text-fill: white

addUserView.wrongUserInfo = Incomplete user information
addUserView.wrongPassword = Passwords do not match
addUserView.failStyle = -fx-background-color: red; -fx-text-fill: black

addUserView.confirmation.title = New user confirmation
addUserView.confirmation.content = Do you want to create the new user?

addUserView.acceptance.title = New user
addUserView.acceptance.content = A new user has been added successfully to the system


#Edit User form
editUserView.default = Edit User
editUserView.defaultStyle = -fx-background-color: black; -fx-text-fill: white

editUserView.userNotFound = User not found
editUserView.wrongUserInfo = Incomplete user information
editUserView.wrongUserCredentials = Incomplete user credentials, password not established.
editUserView.wrongPassword = New passwords do not match
editUserView.failStyle = -fx-background-color: red; -fx-text-fill: black

editUserView.updatedUserConfirmation.title = Update user information confirmation
editUserView.updatedUserConfirmation.content = Do you want to update the user?
editUserView.updatedUserApproval.title = User information updated
editUserView.updatedUserApproval.content = A new user has been updated successfully

editUserView.deletedAccessConfirmation.title = Delete access credentials
editUserView.deletedAccessConfirmation.content = Do you want to delete the user access credentials?
editUserView.deletedAccessApproval.title = Access credentials deleted
editUserView.deletedAccessApproval.content = The user access credentials has been deleted successfully
editUserView.deletedAccessError.title = Delete access credentials error
editUserView.deletedAccessError.content = The user has no access credentials

editUserView.deletedUserConfirmation.title = Delete user
editUserView.deletedUserConfirmation.content = Do you want to delete the user from the com.orderhub.database?
editUserView.deletedUserApproval.title = User deleted
editUserView.deletedUserApproval.content = The user has been deleted successfully
editUserView.deletedUserError.title = Delete user error
editUserView.deletedUserError.content = The user access credentials has been deleted successfully


# Work and Loto procedure lists
procedureLists.default = Work and LOTO procedures lists
procedureLists.defaultStyle = -fx-background-color: black; -fx-text-fill: white

workProcedure.descriptionCode = Document Code
workProcedure.descriptionName = Procedure Name
workProcedure.numProcedures = Number of work procedures:
workProcedure.updatedElement = Procedure updated:
workProcedure.updatedElementError = An error occurred while updating the procedure.
workProcedure.addedElement = Procedure added:
workProcedure.addedElementError = An error occurred while adding the procedure.
workProcedure.deletedElement = Procedure deleted:
workProcedure.deletedElementError = An error occurred while deleting the procedure.
workProcedure.wrongProcedureInfo = Incomplete procedure information.
workProcedure.wrongProcedureCode = The document code is in use, choose a different identification.
workProcedure.noSelection = Select a work procedure.
workProcedure.onList = The document code is in use.

lotoProcedure.descriptionCode = Document Code
lotoProcedure.descriptionName = Procedure Name
lotoProcedure.numProcedures = Number of LOTO procedures:
lotoProcedure.updatedElement = Procedure updated:
lotoProcedure.updatedElementError = An error occurred while updating the procedure.
lotoProcedure.addedElement = Procedure added:
lotoProcedure.addedElementError = An error occurred while adding the procedure.
lotoProcedure.deletedElement = Procedure deleted:
lotoProcedure.deletedElementError = An error occurred while deleting the procedure.
lotoProcedure.wrongProcedureInfo = Incomplete procedure information.
lotoProcedure.wrongProcedureCode = The document code is in use, choose a different identification.
lotoProcedure.noSelection = Select a loto procedure.
lotoProcedure.onList = The document code is in use.


#Plant elements form
plantElement.default = Plant instruments and equipments
plantElement.defaultStyle = -fx-background-color: black; -fx-text-fill: white

plantElement.elementTag = Tag
plantElement.elementDescription = Description
plantElement.elementLocation = Location
plantElement.inspectionDate = Inspection Date
plantElement.inspectionFrequency = Inspection Frequency

plantElement.addedElement = Element added:
plantElement.addedElementError = An error occurred while adding an element.
plantElement.incompleteInfo = Incomplete element information.
plantElement.updatedElement = Element updated:
plantElement.updatedElementError = An error occurred while updating an element.

plantElement.searchTag = Search here!
plantElement.searchList = Tag,Description,Location

plantElement.deletedElementConfirmation.title = Delete plant element
plantElement.deletedElementConfirmation.content = Do you want to delete the element from the com.orderhub.database?
plantElement.deletedElement = element deleted:
plantElement.deletedElementError = An error occurred while deleting the element.


#Spare parts view
spareParts.default = Spare parts inventory
spareParts.defaultStyle = -fx-background-color: black; -fx-text-fill: white

spareParts.itemID = ID
spareParts.itemName = Name
spareParts.partNumber = Part Number
spareParts.itemDescription = Description
spareParts.itemCategory = Category

spareParts.searchTag = Search here!
spareParts.searchList = ID,Name,Part Number
spareParts.stockInfo = Current Stock:
spareParts.outOfStock = Out of stock

spareParts.spareAdded = Added Spare Part:
spareParts.spareAddedError = An error occurred while adding a spare part.
spareParts.incompleteInfo = Incomplete spare part information.

spareParts.deleteSpareConfirmation.title = Delete Spare Part
spareParts.deleteSpareConfirmation.content = Do you want to delete the Spare part item from the system?
spareParts.sparePartDeleted = Spare Part deleted:
spareParts.sparePartDeleteError = An error occurred while deleting the item.

spareParts.updatedSparePart = Updated Spare Part:
spareParts.updatedSparePartError = An error occurred while updating the item.


#Work Order form
workOrder.defaultNew = New Work Order
workOrder.defaultEdit = Edit Work Order
workOrder.defaultStyle = -fx-background-color: black; -fx-text-fill: white
workOrder.failStyle = -fx-background-color: red; -fx-text-fill: black

workOrder.workOrderTab.tagDefault = Tag:
workOrder.workOrderTab.locationDefault = Location:
workOrder.workOrderTab.descriptionDefault = Description:
workOrder.workOrderTab.confirmedTagTitle = Confirmation
workOrder.workOrderTab.confirmedTagMessage = Item added to the work order:

workOrder.workOrderTab.pElementError = Please, insert the tag of the plant element.
workOrder.workOrderTab.pElementNotFound = Item not found, please try again.

workOrder.sparePart.searchTag = Search here!
workOrder.sparePart.searchList = Name,Part Number
workOrder.sparePart.noSelected = Please, select a Spare Part from the list
workOrder.sparePart.outOfStock = Spare part not available.

workOrder.assignment.holderName = NAME:
workOrder.assignment.holderContact = CONTACT:
workOrder.assignment.confTitle = Holder confirmation
workOrder.assignment.confMessage = Holder confirmed for this work permit:
workOrder.assignment.technError = Technician already selected

workOrder.validPeriod.placeHolder = Currently, there are no open work orders.
workOrder.validPeriod.wOrderId = ID
workOrder.validPeriod.startDate = Start Date
workOrder.validPeriod.endDate = End Date
workOrder.validPeriod.description = Description

workOrder.validPeriod.ConfPeriodTitle = Validity period
workOrder.validPeriod.ConfPeriodMessage = Would you like to confirm the selected dates?
workOrder.validPeriod.ConfDates = Dates confirmed.

workOrder.wProcedure.wProcedureId = ID
workOrder.wProcedure.name = Name
workOrder.wProcedure.code = Document Code
workOrder.wProcedure.searchTag = Search here!
workOrder.wProcedure.searchList = ID,Code,Name
workOrder.wProcedure.confWProcedureTitle = Work Procedure
workOrder.wProcedure.confWProcedureMessage = Would you like to confirm the selected Work procedure?
workOrder.wProcedure.codeDefault = Selected WP:
workOrder.wProcedure.wProcedureError = Work procedure already selected
workOrder.wProcedure.noSelected = Please, select a work procedure from the list

workOrder.lotoProcedure.wProcedureId = ID
workOrder.lotoProcedure.name = Name
workOrder.lotoProcedure.code = Document Code
workOrder.lotoProcedure.searchTag = Search here!
workOrder.lotoProcedure.searchList = ID,Code,Name
workOrder.lotoProcedure.confLotoProcedureTitle = LOTO Procedure
workOrder.lotoProcedure.confLotoProcedureMessage = Would you like to confirm the selected LOTO procedure?
workOrder.lotoProcedure.codeDefault = Selected LP:
workOrder.lotoProcedure.lotoProcedureError = LOTO procedure already selected
workOrder.lotoProcedure.noSelected = Please, select a LOTO procedure from the list

workOrder.newWorkOrder.descriptionError = Description not completed
workOrder.newWorkOrder.holderError = Holder not selected
workOrder.newWorkOrder.plantElementError = Plant element not selected
workOrder.newWorkOrder.confWOrderTitle = Create new work order
workOrder.newWorkOrder.confWOrderMessage = Would you like to create and open the work order?

workOrder.newWorkOrder.newWOrderTitle = New work order
workOrder.newWorkOrder.newWOrderMessage = A new work order has been created successfully.
workOrder.newWorkOrder.newWOrderError = An error occurred.

workOrder.newWorkPermit.newWPermitError = Work permit description not completed


# Technician Main View
technicianView.workOrderReviewTitle = Work Order Review

technicianView.default = Assigned Work Orders
technicianView.defaultStyle = -fx-background-color: black; -fx-text-fill: white

technicianView.workOrderId = Work Order ID
technicianView.startDate = Start Date
technicianView.endDate = End Date
technicianView.workProcedureCode = Work Procedure Code
technicianView.holderName = Holder
technicianView.plantElement = Plant Element Tag
technicianView.status = Status

technicianView.closeTitle = Close Work Order
technicianView.closeMessage = Do you want to close the work order selected?

technicianView.noSelectedTitle = Warning
technicianView.noSelectedMessage = Please, select a work order from the list.

technicianView.errorTitle = Warning
technicianView.errorMessage = Work already started.

technicianView.searchTag = Search here!
technicianView.searchList = ID,Tag,Holder,Start Date,End Date


# Work Order Review
workOrderReview.default = Work Order - ID:
workOrderReview.workProcedureError = No work procedure is included.
workOrderReview.workPermitError = No work permit is included.
workOrderReview.lockDeviceError = No lock devices are included.
workOrderReview.lotoProcedureError = No loto Procedure is included.

workOrderReview.commentTitle = Add Comment
workOrderReview.addedComment = The comment has been added to the work order.
workOrderReview.errorComment = An error has occurred during the update.
workOrderReview.noComment = Empty field, please enter your comment.

workOrderReview.editTitle = Edit Spare Part
workOrderReview.removedSparePart = Item removed from the list.
workOrderReview.editedSparePart = The number of items used has been updated.
workOrderReview.editedSparePartError = An error has occurred during the update.
workOrderReview.noSelectedSparePart = Item not selected.


# Supervisor Main View
supervisorView.workOrderReviewTitle = Work Order Review

supervisorView.noSelectedTitle = Warning
supervisorView.noSelectedMessage = Please, select a work order from the list.

SupervisorView.default = Work Orders
SupervisorView.defaultStyle = -fx-background-color: black; -fx-text-fill: white

SupervisorView.workOrderId = Work Order ID
SupervisorView.startDate = Start Date
SupervisorView.endDate = End Date
SupervisorView.workProcedureCode = Work Procedure Code
SupervisorView.lockOutDeviceId = Lock Device ID
SupervisorView.lotoProcedureCode = LOTO Procedure Code
SupervisorView.holderName = Holder
SupervisorView.plantElement = Plant Element Tag
SupervisorView.status = Status

SupervisorView.searchTag = Search here!
SupervisorView.searchList = ID,Tag,Holder,Start Date,End Date