package com.workorderhub.core.caseuse.plantelement;

public enum PlantElementEnum {
    INCOMPLETE_INFORMATION,
    PlANT_ELEMENT_ADDITION_ERROR,
    PLANT_ELEMENT_ADDED,
    PlANT_ELEMENT_UPDATE_ERROR,
    PLANT_ELEMENT_UPDATED,
    CONFIRM_DELETE_PLANT_ELEMENTS,
    PlANT_ELEMENT_DELETION_ERROR,
    PLANT_ELEMENT_DELETED
}
